stages:
  - build

services:
  - docker:stable-dind

build:
  stage: build
  image: docker:stable
  before_script:
    - docker version
    - docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" registry.gitlab.com
  script:
    - docker build --tag "$CI_REGISTRY_IMAGE:$CI_BUILD_REF" .
    - docker tag "$CI_REGISTRY_IMAGE:$CI_BUILD_REF" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:$CI_BUILD_REF" 
    - docker push "$CI_REGISTRY_IMAGE:latest"